### ISSUE TITLE
Why is followSymlinks disabled?

### ISSUE THREAD

**Issue by iMoses** [webpack/watchpack#50]
I have several projects which uses `npm link` to share modules and I've noticed that webpack HMR wouldn't work from these symlinks. 
After investigating I've noticed that in the `chokidar.watch` call passes in the options `followSymlinks: false`.
I wanted to ask how come and if you are willing to change it to `true` :)
That's all I need to use HMR with my `npm link`s.
I can have a PR ready in a minute :)

**Comment by korene** [comment]
This change will definitely make my life easier and will save me time

**Comment by igwan** [comment]
I guess changing `followSymlinks` to `true` by default is not an option since it's one of watchpack concept that
> Symlinks are not followed, instead the symlink is watched.

But maybe we can add it as an option to watchpack while keeping the default to false. This would allow to change it through webpack `watcherOptions`.

Is this acceptable ? Would such a PR be merged ?
I guess a PR for webpack doc would be needed as well.

**Comment by sokra** [comment]
webpack follows symlinks in the resolver. webpack provides both symlink path plus resolved path to watchpack.
